export const ADD_ORDER = 'ADD_ORDER';

export const INCREASE_VALUE = 'INCREASE_VALUE';
export const DECREASE_VALUE = 'DECREASE_VALUE';
export const REMOVE_ORDER = 'REMOVE_ORDER';
export const CHECK_DUPLICATE_ITEM = 'CHECK_DUPLICATE_ITEM';